# Mathematical Operations on tensors
In this tutorial, following topics will be covered:
## Contents of the Tutorial
- mathematical operations
   - Addition
   - Subtraction
   - Multiplication
   - Division
   - Exponent
- Concatenating Tensors
   - Along rows
   - Along Columns 

- Binary Tensors 
- Broadcasting Mechanism
- Indexing and Slicing


In [7]:
# import neccessary packages
import torch

# Mathematical operations 
1. Addition

In [8]:
X = torch.arange(12, dtype = torch.float32).reshape(3, 4)
Y = torch.tensor([[1, 2, 3, 4],
                  [4, 5, 6, 5],
                  [7, 8, 9, 1]], dtype = torch.float32)
X, Y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[1., 2., 3., 4.],
         [4., 5., 6., 5.],
         [7., 8., 9., 1.]]))

In [9]:
X+Y    # element-wise sum

tensor([[ 1.,  3.,  5.,  7.],
        [ 8., 10., 12., 12.],
        [15., 17., 19., 12.]])

2. Subtraction    

In [10]:
X-Y# element-wise subtraction

tensor([[-1., -1., -1., -1.],
        [ 0.,  0.,  0.,  2.],
        [ 1.,  1.,  1., 10.]])

3. Multiplication

In [11]:
X*Y # element-wise Multiplication

tensor([[ 0.,  2.,  6., 12.],
        [16., 25., 36., 35.],
        [56., 72., 90., 11.]])

4. Division

In [12]:
X/Y  # element-wise Division


tensor([[ 0.0000,  0.5000,  0.6667,  0.7500],
        [ 1.0000,  1.0000,  1.0000,  1.4000],
        [ 1.1429,  1.1250,  1.1111, 11.0000]])

# Tensor Concatenation

In [14]:
Z = torch.concat((X, Y), axis=0)
S = torch.concat((X, Y), axis=1)

print(f'shape of the concatenated tensor: {Z.shape}')
S

shape of the concatenated tensor: torch.Size([6, 4])


tensor([[ 0.,  1.,  2.,  3.,  1.,  2.,  3.,  4.],
        [ 4.,  5.,  6.,  7.,  4.,  5.,  6.,  5.],
        [ 8.,  9., 10., 11.,  7.,  8.,  9.,  1.]])

# Check if the elements in two tensors are equal

In [15]:

X.sum()

tensor(66.)

# Broadcasting Mechanism 
Adding two tensor with different shapes


In [17]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))

a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [18]:
a + b                 #broadcasting here

tensor([[0, 1],
        [1, 2],
        [2, 3]])

# Indexing and slicing


In [19]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [20]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [22]:
X[1, 2] = 8
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  8.,  7.],
        [ 8.,  9., 10., 11.]])

In [23]:
X[0:2, :] = 7
X

tensor([[ 7.,  7.,  7.,  7.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  9., 10., 11.]])

# The End